sonar.projectKey=Onoiro_lex
sonar.organization=abo

sonar.language=py
sonar.sources=.
sonar.exclusions=**/tests/**,**/__pycache__/**,**/.venv/**,**/migrations/**,coverage-reports/**,htmlcov/**,.ruff_cache/**,.pytest_cache/**

sonar.tests=.
sonar.test.inclusions=**/tests/**

sonar.python.coverage.reportPaths=coverage-reports/coverage.xml
sonar.python.xunit.reportPath=coverage-reports/test-results.xml
sonar.python.version=3.13
sonar.sourceEncoding=UTF-8
