"""Language metadata: names, native names, and display helpers.

Static dictionaries map ISO language codes to human-readable names
in English and Russian, plus native names (language name in its own language).
Used by the settings page and language selectors.
"""

# Mapping of language codes to English names
LANGUAGE_NAMES_EN = {
    "af": "Afrikaans",
    "sq": "Albanian",
    "am": "Amharic",
    "ar": "Arabic",
    "hy": "Armenian",
    "az": "Azerbaijani",
    "ba": "Bashkir",
    "bua": "Buryat",
    "be": "Belarusian",
    "bn": "Bengali",
    "bs": "Bosnian",
    "bg": "Bulgarian",
    "ca": "Catalan",
    "ceb": "Cebuano",
    "zh": "Chinese",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "nl": "Dutch",
    "en": "English",
    "eo": "Esperanto",
    "et": "Estonian",
    "ht": "Haitian Creole",
    "kv": "Komi",
    "fi": "Finnish",
    "fr": "French",
    "ka": "Georgian",
    "de": "German",
    "el": "Greek",
    "gu": "Gujarati",
    "ha": "Hausa",
    "he": "Hebrew",
    "hi": "Hindi",
    "hu": "Hungarian",
    "is": "Icelandic",
    "id": "Indonesian",
    "ga": "Irish",
    "it": "Italian",
    "ja": "Japanese",
    "jv": "Javanese",
    "kn": "Kannada",
    "kk": "Kazakh",
    "km": "Khmer",
    "tlh": "Klingon",
    "ko": "Korean",
    "ky": "Kyrgyz",
    "lo": "Lao",
    "la": "Latin",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "ms": "Malay",
    "mt": "Maltese",
    "mk": "Macedonian",
    "mr": "Marathi",
    "my": "Myanmar",
    "mn": "Mongolian",
    "ne": "Nepali",
    "no": "Norwegian",
    "fa": "Persian",
    "pl": "Polish",
    "pt": "Portuguese",
    "pa": "Punjabi",
    "ro": "Romanian",
    "ru": "Russian",
    "sr": "Serbian",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "so": "Somali",
    "es": "Spanish",
    "sw": "Swahili",
    "sv": "Swedish",
    "tg": "Tajik",
    "ta": "Tamil",
    "te": "Telugu",
    "th": "Thai",
    "to": "Tongan",
    "tr": "Turkish",
    "tk": "Turkmen",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "uz": "Uzbek",
    "vi": "Vietnamese",
    "cy": "Welsh",
    "zu": "Zulu",
    "ce": "Chechen",
    "cv": "Chuvash",
    "eu": "Basque",
    "gl": "Galician",
    "mg": "Malagasy",
    "pap": "Papiamento",
    "xh": "Xhosa",
    "tl": "Filipino",
    "su": "Sundanese",
    "emj": "Emoji",
    "lb": "Luxembourgish",
    "mi": "Maori",
    "tt": "Tatar",
    "yi": "Yiddish",
    "ab": "Abkhaz",
    "abq": "Abaza",
    "gd": "Scottish Gaelic",
    "kazlat": "Kazakh (Latin)",
    "kbd": "Kabardian",
    "kjh": "Khakas",
    "krc": "Karachay-Balkar",
    "mdf": "Moksha",
    "mhr": "Eastern Mari",
    "mns": "Mansi",
    "mrj": "Western Mari",
    "myv": "Erzya",
    "nog": "Nogai",
    "os": "Ossetian",
    "pt-BR": "Portuguese (Brazil)",
    "sah": "Yakut",
    "sr-Latn": "Serbo-Croatian (Latin)",
    "tyv": "Tuvan",
    "udm": "Udmurt",
    "uzbcyr": "Uzbek (Cyrillic)",
}


# Mapping of language codes to Russian names
LANGUAGE_NAMES_RU = {
    "af": "Африкаанс",
    "sq": "Албанский",
    "am": "Амхарский",
    "ar": "Арабский",
    "hy": "Армянский",
    "az": "Азербайджанский",
    "ba": "Башкирский",
    "be": "Белорусский",
    "bn": "Бенгальский",
    "bs": "Боснийский",
    "bg": "Болгарский",
    "ca": "Каталанский",
    "zh": "Китайский",
    "hr": "Хорватский",
    "cs": "Чешский",
    "da": "Датский",
    "nl": "Нидерландский",
    "en": "Английский",
    "eo": "Эсперанто",
    "et": "Эстонский",
    "ht": "Гаитянский креольский",
    "fi": "Финский",
    "kv": "Коми",
    "fr": "Французский",
    "ka": "Грузинский",
    "de": "Немецкий",
    "el": "Греческий",
    "gu": "Гуджарати",
    "ha": "Хауса",
    "he": "Иврит",
    "hi": "Хинди",
    "hu": "Венгерский",
    "is": "Исландский",
    "id": "Индонезийский",
    "ga": "Ирландский",
    "it": "Итальянский",
    "ja": "Японский",
    "jv": "Яванский",
    "kn": "Каннада",
    "kk": "Казахский",
    "km": "Кхмерский",
    "tlh": "Клингонский",
    "ko": "Корейский",
    "ky": "Киргизский",
    "lo": "Лаосский",
    "la": "Латинский",
    "lv": "Латышский",
    "ms": "Малайский",
    "mt": "Мальтийский",
    "mk": "Македонский",
    "mr": "Маратхи",
    "my": "Мьянма",
    "mn": "Монгольский",
    "ne": "Непальский",
    "no": "Норвежский",
    "fa": "Персидский",
    "pl": "Польский",
    "pt": "Португальский",
    "pa": "Панджаби",
    "ro": "Румынский",
    "ru": "Русский",
    "sr": "Сербский",
    "si": "Сингальский",
    "sk": "Словацкий",
    "sl": "Словенский",
    "so": "Сомалийский",
    "es": "Испанский",
    "sw": "Суахили",
    "sv": "Шведский",
    "tg": "Таджикский",
    "ta": "Тамильский",
    "te": "Телугу",
    "th": "Тайский",
    "to": "Тонганский",
    "tr": "Турецкий",
    "tk": "Туркменский",
    "uk": "Украинский",
    "ur": "Урду",
    "uz": "Узбекский",
    "vi": "Вьетнамский",
    "cy": "Валлийский",
    "zu": "Зулу",
    "ce": "Чеченский",
    "cv": "Чувашский",
    "bua": "Бурятский",
    "ceb": "Себуанский",
    "eu": "Баскский",
    "gl": "Галисийский",
    "mg": "Малагасийский",
    "pap": "Папьяменто",
    "xh": "Коса",
    "tl": "Филиппинский",
    "su": "Сунданский",
    "emj": "Эмоджи",
    "lb": "Люксембургский",
    "mi": "Маори",
    "tt": "Татарский",
    "yi": "Идиш",
    "ab": "Абхазский",
    "abq": "Абазинский",
    "gd": "Шотландский гэльский",
    "kazlat": "Казахский (латиница)",
    "kbd": "Кабардинский",
    "kjh": "Хакасский",
    "krc": "Карачаево-балкарский",
    "mdf": "Мокшанский",
    "mhr": "Луговомарийский",
    "mns": "Мансийский",
    "mrj": "Горномарийский",
    "myv": "Эрзянский",
    "nog": "Ногайский",
    "os": "Осетинский",
    "pt-BR": "Португальский (Бразилия)",
    "sah": "Якутский",
    "sr-Latn": "Сербскохорватский (латиница)",
    "tyv": "Тувинский",
    "udm": "Удмуртский",
    "uzbcyr": "Узбекский (кириллица)",
}


# Mapping of language codes to native names (language name in its own language)
NATIVE_NAMES = {
    "en": "English",
    "es": "Español",
    "fr": "Français",
    "de": "Deutsch",
    "it": "Italiano",
    "pt": "Português",
    "ru": "Русский",
    "zh": "中文",
    "ja": "日本語",
    "ko": "한국어",
    "ar": "العربية",
    "hi": "हिन्दी",
    "tr": "Türkçe",
    "pl": "Polski",
    "nl": "Nederlands",
    "uk": "Українська",
    "sv": "Svenska",
    "cs": "Čeština",
    "el": "Ελληνικά",
    "hu": "Magyar",
    "fi": "Suomi",
    "no": "Norsk",
    "da": "Dansk",
    "ro": "Română",
    "th": "ไทย",
    "vi": "Tiếng Việt",
    "id": "Bahasa Indonesia",
    "he": "עברית",
    "bg": "Български",
    "ca": "Català",
    "hr": "Hrvatski",
    "sk": "Slovenčina",
    "sl": "Slovenščina",
    "sr": "Српски",
    "ms": "Bahasa Melayu",
    "tl": "Filipino",
    "af": "Afrikaans",
    "sq": "Shqip",
    "am": "አማርኛ",
    "az": "Azərbaycan",
    "be": "Беларуская",
    "bn": "বাংলা",
    "bs": "Bosanski",
    "cy": "Cymraeg",
    "et": "Eesti",
    "fa": "فارسی",
    "ga": "Gaeilge",
    "gl": "Galego",
    "gu": "ગુજરાતી",
    "ha": "Hausa",
    "hy": "Հայերեն",
    "is": "Íslenska",
    "jw": "Basa Jawa",
    "jv": "Basa Jawa",
    "ka": "ქართული",
    "kk": "Қазақша",
    "km": "ខ្មែរ",
    "kn": "ಕನ್ನಡ",
    "ky": "Кыргызча",
    "lo": "ລາວ",
    "la": "Latina",
    "lt": "Lietuvių",
    "lv": "Latviešu",
    "mk": "Македонски",
    "ml": "മലയാളം",
    "mn": "Монгол",
    "mr": "मराठी",
    "mt": "Malti",
    "my": "မြန်မာ",
    "ne": "नेपाली",
    "ps": "پښتو",
    "pa": "ਪੰਜਾਬੀ",
    "si": "සිංහල",
    "so": "Soomaali",
    "sw": "Kiswahili",
    "ta": "தமிழ்",
    "te": "తెలుగు",
    "tg": "Тоҷикӣ",
    "tk": "Türkmençe",
    "tlh": "tlhIngan Hol",
    "to": "lea fakatonga",
    "tt": "Татарча",
    "ur": "اردو",
    "uz": "Oʻzbekcha",
    "xh": "isiXhosa",
    "yi": "ייִדיש",
    "zu": "isiZulu",
    "ba": "Башҡортса",
    "ce": "Доьллат",
    "cv": "Чӑвашла",
    "bua": "Буряад хэлэн",
    "ceb": "Bisayâ",
    "eu": "euskara",
    "mg": "Malagasy",
    "pap": "Papiamentu",
    "su": "basa Sunda",
    "emj": "Emoji",
    "lb": "Lëtzebuergesch",
    "mi": "reo Māori",
    "ht": "Kreyòl ayisyen",
    "eo": "Esperanto",
    "kv": "Коми кыв",
    "ab": "Аԥсуа бызшәа",
    "abq": "Абаза бызшва",
    "gd": "Gàidhlig",
    "kazlat": "Қазақша",
    "kbd": "Адыгэбзэ",
    "kjh": "Хакас тілі",
    "krc": "Къарачай-малкъар тил",
    "mdf": "Мокшень кяль",
    "mhr": "Олык марий",
    "mns": "Ма̄ньщи ла̄тыӈ",
    "mrj": "Кырык мары",
    "myv": "Эрзянь кель",
    "nog": "Ногай тили",
    "os": "Ирон",
    "pt-BR": "Português",
    "sah": "Саха тыла",
    "sr-Latn": "srpskohrvatski",
    "tyv": "Тыва дыл",
    "udm": "Удмурт кыл",
    "uzbcyr": "Ўзбекча",
}


def get_language_name(code: str) -> str:
    """Return a human-readable English name for a language code.
    
    Falls back to the code itself if unknown.
    
    Args:
        code: ISO language code (e.g. 'en', 'ce', 'ru').
        
    Returns:
        English language name.
    """
    return LANGUAGE_NAMES_EN.get(code, code)
